### ISSUE TITLE
Make the application compatible with XWiki 6.4.x

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-cookie-consent#19]
Some users having XWiki 6.4.x might benefit from the application if they are using XWiki for a public website.

**Comment by petrenkonikita112263** [comment]
Fixed, but not closed.

**Comment by mflorea** [comment]
@petrenkonikita112263 no, there is one commit, but it's on a branch that hasn't been merged. The current parent is 8.4 so XWiki 6.4 is not supported. The Pro Apps policy is to support one LTS behind the current LTS (14.10.x), so we need to upgrade to 13.10.x. Supporting 6.4 is too costly.
