### ISSUE TITLE
Allowing to select the type of cookies to be displayed on the popup

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-cookie-consent#22]
Hi,

The type of cookie category to be displayed on the popup should be selectable from the configuration page of the Cookie Consent app.

For example, on the XWiki Store, there was a modification done to display only the Necessary and the Statistics categories on the popup.

![image](https://user-images.githubusercontent.com/36840106/70049666-d68cf200-15d5-11ea-99ef-2a69ee18160b.png)

Thank you.

**Comment by acotiuga** [comment]
In the Administration section, there is a new configurable property that will allow an Admin user to display any cookie type. If none if them is selected, the cookie notification pop-up will not be displayed anymore, just like it would be disabled.
With this improvement, the application provides more flexibility and even the mandatory cookie could be disabled, if needed.

![activeCookieTypes](https://user-images.githubusercontent.com/8121819/113886341-45c9b600-97c9-11eb-97d1-c1f0b23ef59e.png)
