### ISSUE TITLE
The GDPR Cookie Consent administration page is not removed after application uninstall

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-cookie-consent#37]
**Environment**: Windows 11 Pro 64bit, Chrome 102, using a local instance of XWiki 14.4, Java 17 (Oracle), **GDPR Cookie Consent 1.2.6**

STEPS TO REPRODUCE

1. Uninstall GDPR Cookie Consent application
2. Go to Administer Wiki > Other
3. Observe the accordion

EXPECTED RESULTS

The page related to GDPR Cookie Consent application is removed.

ACTUAL RESULTS

The configuration page is still there and it contains only the following string `cookieConsent.administration.heading`.

![image](https://user-images.githubusercontent.com/32512703/171847556-ef3acd75-a0be-444b-ac5e-a104f705a351.png)

**Comment by petrenkonikita112263** [comment]
The issue isn't relevant, since it's not reproduced on the latest version (1.2.8).
